const questions = {
  food: [
    {
      emojis: ["🍎", "🍌", "🥕"],
      answer: "perishable",
      options: ["perishable", "non-perishable", "processed", "canned"],
      hint: "These foods can spoil quickly if not stored properly.",
    },
    {
      emojis: ["🍕", "🍔", "🌭"],
      answer: "fast food",
      options: ["gourmet", "fast food", "organic", "vegan"],
      hint: "Quick, convenient meals often associated with chain restaurants.",
    },
    {
      emojis: ["🍣", "🍜", "🍱"],
      answer: "Asian cuisine",
      options: [
        "European cuisine",
        "African cuisine",
        "Asian cuisine",
        "American cuisine",
      ],
      hint: "Culinary traditions from the world's largest continent.",
    },
    {
      emojis: ["🥑", "🥬", "🥦"],
      answer: "superfood",
      options: ["junk food", "superfood", "processed food", "comfort food"],
      hint: "Foods believed to be nutritionally dense and good for one's health.",
    },
    {
      emojis: ["🍷", "🧀"],
      answer: "fermentation",
      options: [
        "preservation",
        "fermentation",
        "pasteurization",
        "dehydration",
      ],
      hint: "A metabolic process that produces chemical changes in organic substrates through the action of enzymes.",
    },
    {
      emojis: ["🌶️", "🥵", "💧"],
      answer: "capsaicin",
      options: ["umami", "capsaicin", "tannin", "pectin"],
      hint: "The compound that gives chili peppers their spicy heat.",
    },
  ],
  animals: [
    {
      emojis: ["🐶", "🐱", "🐹"],
      answer: "mammal",
      options: ["reptile", "mammal", "amphibian", "bird"],
      hint: "This class of animals is warm-blooded and usually has fur.",
    },
    {
      emojis: ["🦁", "🐯", "🐆"],
      answer: "big cats",
      options: ["primates", "big cats", "marine mammals", "marsupials"],
      hint: "Large felines, often apex predators in their ecosystems.",
    },
    {
      emojis: ["🐘", "🦏", "🦛"],
      answer: "megafauna",
      options: ["insects", "megafauna", "reptiles", "fish"],
      hint: "Large or giant animals, often referring to those weighing over 40 kg.",
    },
    {
      emojis: ["🦅", "🦉", "🦜"],
      answer: "birds of prey",
      options: ["flightless birds", "birds of prey", "waterfowl", "songbirds"],
      hint: "Birds that hunt and feed on other animals.",
    },
    {
      emojis: ["🐒", "🦍", "🦧"],
      answer: "primates",
      options: ["carnivores", "primates", "cetaceans", "ungulates"],
      hint: "An order of mammals that includes monkeys, apes, and humans.",
    },
    {
      emojis: ["🦎", "🐍"],
      answer: "herpetology",
      options: ["ichthyology", "herpetology", "ornithology", "entomology"],
      hint: "The branch of zoology concerned with the study of amphibians and reptiles.",
    },
  ],
  transport: [
    {
      emojis: ["🚗", "🚕", "🚙"],
      answer: "vehicle",
      options: ["vehicle", "building", "furniture", "appliance"],
      hint: "A general term for any form of transportation.",
    },
    {
      emojis: ["🚂", "🚅", "🚊"],
      answer: "rail transport",
      options: [
        "air transport",
        "sea transport",
        "rail transport",
        "road transport",
      ],
      hint: "A method of transport that uses a track or guideway for vehicles.",
    },
    {
      emojis: ["🛳️", "⛴️", "🚢"],
      answer: "maritime transport",
      options: [
        "aviation",
        "maritime transport",
        "public transit",
        "space travel",
      ],
      hint: "The transport of people or goods via waterways.",
    },
    {
      emojis: ["🚁", "✈️", "🛩️"],
      answer: "aviation",
      options: ["navigation", "aviation", "locomotion", "propulsion"],
      hint: "The activities surrounding mechanical flight and the aircraft industry.",
    },
    {
      emojis: ["🚗", "🔌"],
      answer: "electric vehicle",
      options: [
        "hybrid car",
        "electric vehicle",
        "fuel cell",
        "combustion engine",
      ],
      hint: "A type of vehicle that uses one or more electric motors for propulsion.",
    },
    {
      emojis: ["🚀", "🛰️", "🌌"],
      answer: "aerospace",
      options: ["aeronautics", "aerospace", "astronautics", "astrophysics"],
      hint: "The branch of technology and industry concerned with both aviation and space flight.",
    },
  ],
  sports: [
    {
      emojis: ["🏀", "⚽", "🎾"],
      answer: "sport",
      options: ["art", "music", "sport", "cooking"],
      hint: "Physical activities often involving competition.",
    },
    {
      emojis: ["🏊", "🚴", "🏃"],
      answer: "triathlon",
      options: ["pentathlon", "decathlon", "triathlon", "marathon"],
      hint: "A multi-sport event involving these three activities.",
    },
    {
      emojis: ["🥊", "🤼", "🤺"],
      answer: "combat sports",
      options: [
        "team sports",
        "water sports",
        "combat sports",
        "winter sports",
      ],
      hint: "Athletic competitions involving one-on-one physical confrontations.",
    },
    {
      emojis: ["⛷️", "🏂", "🛷"],
      answer: "winter sports",
      options: [
        "summer sports",
        "indoor sports",
        "water sports",
        "winter sports",
      ],
      hint: "Athletic activities that are played on snow or ice.",
    },
    {
      emojis: ["🏋️", "💪"],
      answer: "strength training",
      options: ["cardio", "flexibility", "strength training", "balance"],
      hint: "Physical exercise specializing in the use of resistance to induce muscular contraction.",
    },
    {
      emojis: ["🧘", "🧠", "😌"],
      answer: "mindfulness",
      options: ["endurance", "agility", "mindfulness", "coordination"],
      hint: "The practice of maintaining a nonjudgmental state of heightened or complete awareness of one's thoughts, emotions, or experiences on a moment-to-moment basis.",
    },
  ],
  nature: [
    {
      emojis: ["🌳", "🌿", "🍄"],
      answer: "ecosystem",
      options: ["economy", "ecosystem", "society", "galaxy"],
      hint: "A biological community of interacting organisms and their physical environment.",
    },
    {
      emojis: ["🌋", "🏔️", "🏜️"],
      answer: "landforms",
      options: [
        "weather patterns",
        "landforms",
        "water bodies",
        "atmospheric layers",
      ],
      hint: "Natural features of the Earth's surface.",
    },
    {
      emojis: ["🌊", "🌬️", "☀️"],
      answer: "weather",
      options: ["climate", "weather", "season", "atmosphere"],
      hint: "The day-to-day state of the atmosphere, and its short-term variation.",
    },
    {
      emojis: ["🐝", "🦋", "🐞"],
      answer: "pollinators",
      options: ["predators", "pollinators", "decomposers", "producers"],
      hint: "Animals that help plants reproduce by transferring pollen.",
    },
    {
      emojis: ["🌡️", "🌍", "🏭"],
      answer: "global warming",
      options: ["deforestation", "global warming", "biodiversity", "pollution"],
      hint: "The long-term heating of Earth's climate system observed since the pre-industrial period.",
    },
    {
      emojis: ["🌳", "🐘", "🐒"],
      answer: "biodiversity",
      options: ["ecosystem", "habitat", "biodiversity", "conservation"],
      hint: "The variety of life in the world or in a particular habitat or ecosystem.",
    },
  ],
  technology: [
    {
      emojis: ["💻", "📱", "🤖"],
      answer: "digital",
      options: ["analog", "digital", "organic", "mechanical"],
      hint: "Relating to computer technology and electronic systems.",
    },
    {
      emojis: ["🔋", "💡", "🔌"],
      answer: "electricity",
      options: ["magnetism", "gravity", "electricity", "nuclear power"],
      hint: "A form of energy resulting from the existence of charged particles.",
    },
    {
      emojis: ["📡", "🛰️", "🔭"],
      answer: "telecommunications",
      options: [
        "transportation",
        "telecommunications",
        "manufacturing",
        "agriculture",
      ],
      hint: "The transmission of information by various types of technologies over wire, radio, optical, or other electromagnetic systems.",
    },
    {
      emojis: ["🧬", "💊", "🔬"],
      answer: "biotechnology",
      options: [
        "nanotechnology",
        "biotechnology",
        "robotics",
        "quantum computing",
      ],
      hint: "Technology that utilizes biological systems, living organisms, or their derivatives to develop or create different products.",
    },
    {
      emojis: ["🤖", "🧠", "💻"],
      answer: "artificial intelligence",
      options: [
        "virtual reality",
        "artificial intelligence",
        "quantum computing",
        "blockchain",
      ],
      hint: "The simulation of human intelligence processes by machines, especially computer systems.",
    },
    {
      emojis: ["🔒", "🔑", "📊"],
      answer: "blockchain",
      options: [
        "encryption",
        "blockchain",
        "quantum cryptography",
        "steganography",
      ],
      hint: "A decentralized, distributed ledger technology that records transactions across many computers.",
    },
    {
      emojis: ["👓", "🖥️"],
      answer: "augmented reality",
      options: [
        "virtual reality",
        "augmented reality",
        "holography",
        "3D printing",
      ],
      hint: "An interactive experience where the real-world environment is enhanced with computer-generated information.",
    },
  ],
  science: [
    {
      emojis: ["🧬", "🔬", "💊"],
      answer: "biotechnology",
      options: ["chemistry", "biotechnology", "physics", "geology"],
      hint: "The use of living systems and organisms to develop or make products.",
    },
    {
      emojis: ["🌋", "🌡️"],
      answer: "geothermal",
      options: ["seismic", "geothermal", "atmospheric", "tectonic"],
      hint: "Relating to or produced by the internal heat of the earth.",
    },
    {
      emojis: ["🔬", "🧫", "🦠"],
      answer: "microbiology",
      options: ["astronomy", "microbiology", "ecology", "genetics"],
      hint: "The study of microorganisms, such as bacteria and viruses.",
    },
    {
      emojis: ["🌌", "🕳️"],
      answer: "black hole",
      options: ["galaxy", "nebula", "black hole", "supernova"],
      hint: "A region of spacetime where gravity is so strong that nothing can escape from it.",
    },
    {
      emojis: ["⚛️", "🔬"],
      answer: "quantum mechanics",
      options: [
        "relativity",
        "quantum mechanics",
        "thermodynamics",
        "electromagnetism",
      ],
      hint: "The fundamental theory of nature at the smallest scales of energy levels of atoms and subatomic particles.",
    },
    {
      emojis: ["🧪", "🔥", "💨"],
      answer: "chemical reaction",
      options: [
        "physical change",
        "chemical reaction",
        "nuclear decay",
        "phase transition",
      ],
      hint: "A process that leads to the transformation of one set of chemical substances to another.",
    },
    {
      emojis: ["🧬", "🔀", "🐁"],
      answer: "CRISPR",
      options: ["CRISPR", "PCR", "Electrophoresis", "Southern blot"],
      hint: "A gene-editing technology that allows for precise modifications of DNA sequences.",
    },
    {
      emojis: ["🌌", "🌀", "🕳️"],
      answer: "quasar",
      options: ["nebula", "quasar", "pulsar", "magnetar"],
      hint: "An extremely luminous active galactic nucleus, powered by a supermassive black hole.",
    },
    {
      emojis: ["🧠", "⚡", "💊"],
      answer: "neurotransmitter",
      options: [
        "synapse",
        "neurotransmitter",
        "action potential",
        "myelin sheath",
      ],
      hint: "Chemical messengers that transmit signals across a chemical synapse.",
    },
  ],
  culture: [
    {
      emojis: ["🎭", "📚", "🎨"],
      answer: "humanities",
      options: ["fine arts", "humanities", "social sciences", "liberal arts"],
      hint: "Academic disciplines that study human culture and experience.",
    },
    {
      emojis: ["🗣️", "🌐"],
      answer: "globalization",
      options: ["immigration", "globalization", "diplomacy", "trade"],
      hint: "The process by which businesses or other organizations develop international influence or start operating on an international scale.",
    },
    {
      emojis: ["👥", "💬", "🤝"],
      answer: "intercultural communication",
      options: [
        "sociology",
        "anthropology",
        "intercultural communication",
        "linguistics",
      ],
      hint: "The study of communication across different cultures and social groups.",
    },
    {
      emojis: ["🏛️", "📜"],
      answer: "cultural heritage",
      options: ["archaeology", "cultural heritage", "history", "museology"],
      hint: "The legacy of physical artifacts and intangible attributes of a group or society that are inherited from past generations.",
    },
    {
      emojis: ["🎭", "🎬", "📺"],
      answer: "performing arts",
      options: [
        "visual arts",
        "performing arts",
        "literary arts",
        "culinary arts",
      ],
      hint: "Forms of creative activity that are performed in front of an audience, such as drama, music, and dance.",
    },
    {
      emojis: ["🗿", "🏺", "⚱️"],
      answer: "archaeology",
      options: ["paleontology", "archaeology", "anthropology", "geology"],
      hint: "The study of human history and prehistory through the excavation of sites and the analysis of artifacts and other physical remains.",
    },
  ],
  everyday_life: [
    {
      emojis: ["🛏️", "⏰", "🌅"],
      answer: "wake up",
      options: ["sleep in", "wake up", "take a nap", "hit snooze"],
      hint: "The act of rising from sleep, often accompanied by an alarm.",
    },
    {
      emojis: ["🚿", "🧼", "🎵"],
      answer: "shower singing",
      options: ["bath time", "shower singing", "water dance", "soap opera"],
      hint: "A common habit of performing vocal exercises while bathing.",
    },
    {
      emojis: ["📱", "👍", "💬"],
      answer: "social media",
      options: ["texting", "phone call", "social media", "email"],
      hint: "Online platforms for sharing content and interacting with others.",
    },
    {
      emojis: ["🏠", "🧹", "🧼"],
      answer: "spring cleaning",
      options: [
        "house party",
        "spring cleaning",
        "home renovation",
        "feng shui",
      ],
      hint: "An annual tradition of thoroughly cleaning one's living space.",
    },
    {
      emojis: ["🛒", "📝", "🏪"],
      answer: "grocery shopping",
      options: [
        "window shopping",
        "online shopping",
        "grocery shopping",
        "bargain hunting",
      ],
      hint: "The task of purchasing food and household supplies.",
    },
  ],
};
