const questions = {
  daily: [
    {
      emojis: ["🦋", "🌪️", "🦜"],
      answer: "chaos theory",
      options: ["chaos theory", "string theory", "game theory", "set theory"],
      hint: "A scientific concept that small changes can lead to big differences in complex systems.",
    },
    {
      emojis: ["🧠", "💊", "🎭"],
      answer: "cognitive dissonance",
      options: [
        "confirmation bias",
        "cognitive dissonance",
        "placebo effect",
        "halo effect",
      ],
      hint: "The mental discomfort experienced when your beliefs don't align with your actions.",
    },
    // {
    //   emojis: ["🌍", "💺", "🚀"],
    //   answer: "escape velocity",
    //   options: [
    //     "escape velocity",
    //     "terminal velocity",
    //     "orbital velocity",
    //     "impact velocity",
    //   ],
    //   hint: "The speed needed to break free from a planet's gravitational pull.",
    // },
    // {
    //   emojis: ["🕰️", "➿", "🌌"],
    //   answer: "spacetime continuum",
    //   options: [
    //     "spacetime continuum",
    //     "multiverse theory",
    //     "quantum entanglement",
    //     "event horizon",
    //   ],
    //   hint: "A mathematical model that combines space and time into a single interwoven continuum.",
    // },
    // {
    //   emojis: ["🧬", "🔀", "🐒"],
    //   answer: "evolutionary psychology",
    //   options: [
    //     "behavioral psychology",
    //     "evolutionary psychology",
    //     "cognitive psychology",
    //     "developmental psychology",
    //   ],
    //   hint: "The study of psychological traits and behaviors in terms of natural selection.",
    // },
    // {
    //   emojis: ["🎭", "🤖", "🧠"],
    //   answer: "turing test",
    //   options: [
    //     "turing test",
    //     "heisenberg uncertainty principle",
    //     "schrodinger's cat",
    //     "occam's razor",
    //   ],
    //   hint: "A test of a machine's ability to exhibit intelligent behavior equivalent to a human.",
    // },
    // {
    //   emojis: ["🌊", "🏃‍♂️", "⏳"],
    //   answer: "flow state",
    //   options: [
    //     "flow state",
    //     "resting state",
    //     "fight-or-flight response",
    //     "REM sleep",
    //   ],
    //   hint: "A mental state of complete absorption in an activity, often leading to peak performance.",
    // },
    // {
    //   emojis: ["🧲", "🌡️", "💨"],
    //   answer: "plasma",
    //   options: ["solid", "liquid", "gas", "plasma"],
    //   hint: "The fourth state of matter, consisting of ionized gas.",
    // },
    // {
    //   emojis: ["🔊", "🌳", "❓"],
    //   answer: "schrodinger's cat",
    //   options: [
    //     "schrodinger's cat",
    //     "pavlov's dog",
    //     "newton's cradle",
    //     "tesla coil",
    //   ],
    //   hint: "A thought experiment in quantum mechanics involving a cat that may be simultaneously alive and dead.",
    // },
    // {
    //   emojis: ["🧠", "👥", "🎭"],
    //   answer: "collective unconscious",
    //   options: [
    //     "collective unconscious",
    //     "groupthink",
    //     "mob mentality",
    //     "herd behavior",
    //   ],
    //   hint: "Carl Jung's theory of a shared, inherited reservoir of memory and experience of our species.",
    // },
    // {
    //   emojis: ["🦠", "🧬", "🔁"],
    //   answer: "horizontal gene transfer",
    //   options: [
    //     "vertical gene transfer",
    //     "horizontal gene transfer",
    //     "genetic drift",
    //     "gene expression",
    //   ],
    //   hint: "The movement of genetic material between organisms other than by reproduction.",
    // },
    // {
    //   emojis: ["🌍", "🔄", "☀️"],
    //   answer: "milankovitch cycles",
    //   options: [
    //     "milankovitch cycles",
    //     "keeling curve",
    //     "hubble sequence",
    //     "drake equation",
    //   ],
    //   hint: "Variations in Earth's orbit that influence long-term climate patterns.",
    // },
    // {
    //   emojis: ["🧠", "🔍", "💡"],
    //   answer: "paradigm shift",
    //   options: [
    //     "paradigm shift",
    //     "cognitive bias",
    //     "mental model",
    //     "brainstorming",
    //   ],
    //   hint: "A fundamental change in approach or underlying assumptions, often in science or culture.",
    // },
    // {
    //   emojis: ["🌌", "🕳️", "🔭"],
    //   answer: "event horizon",
    //   options: ["event horizon", "singularity", "wormhole", "black hole"],
    //   hint: "The boundary around a black hole beyond which events cannot affect an outside observer.",
    // },
    // {
    //   emojis: ["🧬", "🔒", "🗝️"],
    //   answer: "epigenetics",
    //   options: ["genetics", "epigenetics", "genomics", "proteomics"],
    //   hint: "The study of changes in organisms caused by modification of gene expression rather than alteration of the genetic code itself.",
    // },
    // {
    //   emojis: ["🌊", "🏝️", "🔄"],
    //   answer: "punctuated equilibrium",
    //   options: [
    //     "gradualism",
    //     "uniformitarianism",
    //     "punctuated equilibrium",
    //     "catastrophism",
    //   ],
    //   hint: "A theory in evolutionary biology where species are generally stable, but experience rare bursts of rapid change.",
    // },
    // {
    //   emojis: ["🧠", "👁️", "🌈"],
    //   answer: "qualia",
    //   options: ["cognition", "consciousness", "qualia", "perception"],
    //   hint: "Individual instances of subjective, conscious experience.",
    // },
    // {
    //   emojis: ["🦋", "👣", "🌪️"],
    //   answer: "butterfly effect",
    //   options: [
    //     "ripple effect",
    //     "domino effect",
    //     "butterfly effect",
    //     "snowball effect",
    //   ],
    //   hint: "The sensitive dependence on initial conditions in which a small change can result in large differences later.",
    // },
    // {
    //   emojis: ["🧠", "🤝", "🌐"],
    //   answer: "hive mind",
    //   options: ["hive mind", "groupthink", "mob mentality", "herd behavior"],
    //   hint: "A collective consciousness or intelligence formed by a group of individuals.",
    // },
    // {
    //   emojis: ["🔬", "🧫", "🦠"],
    //   answer: "extremophile",
    //   options: ["extremophile", "thermophile", "halophile", "acidophile"],
    //   hint: "An organism that thrives in physically or geochemically extreme conditions.",
    // },
  ],
  food: [
    {
      emojis: ["🍎", "🍌", "🥕"],
      answer: "perishable",
      options: ["perishable", "non-perishable", "processed", "canned"],
      hint: "These foods can spoil quickly if not stored properly.",
    },
    {
      emojis: ["🍕", "🍔", "🌭"],
      answer: "fast food",
      options: ["gourmet", "fast food", "organic", "vegan"],
      hint: "Quick, convenient meals often associated with chain restaurants.",
    },
    {
      emojis: ["🍣", "🍜", "🍱"],
      answer: "Japanese cuisine",
      options: [
        "European cuisine",
        "African cuisine",
        "Asian cuisine",
        "American cuisine",
      ],
      hint: "Culinary traditions from the world's largest continent.",
    },
    {
      emojis: ["🥑", "🥬", "🥦"],
      answer: "superfood",
      options: ["junk food", "superfood", "processed food", "comfort food"],
      hint: "Foods believed to be nutritionally dense and good for one's health.",
    },
    {
      emojis: ["🍷", "🧀"],
      answer: "fermentation",
      options: [
        "preservation",
        "fermentation",
        "pasteurization",
        "dehydration",
      ],
      hint: "A metabolic process that produces chemical changes in organic substrates through the action of enzymes.",
    },
    {
      emojis: ["🌶️", "🥵", "💧"],
      answer: "capsaicin",
      options: ["umami", "capsaicin", "tannin", "pectin"],
      hint: "The compound that gives chili peppers their spicy heat.",
    },
    {
      emojis: ["🥚", "🍳", "🧑‍🍳"],
      answer: "culinary",
      options: ["baking", "culinary", "nutrition", "agriculture"],
      hint: "The art of preparing and cooking food.",
    },
    {
      emojis: ["🍖", "🔥", "🍗"],
      answer: "barbecue",
      options: ["roasting", "frying", "barbecue", "boiling"],
      hint: "A cooking method involving grilling food over an open fire.",
    },
    {
      emojis: ["🥕", "🔪", "🥗"],
      answer: "salad",
      options: ["soup", "stew", "salad", "stir-fry"],
      hint: "A dish of various mixtures of raw or cooked vegetables, usually served cold.",
    },
    {
      emojis: ["🍞", "🧈", "🔪"],
      answer: "sandwich",
      options: ["toast", "pastry", "sandwich", "breadsticks"],
      hint: "A food item consisting of fillings between slices of bread.",
    },
    {
      emojis: ["🥛", "🐮", "🧀"],
      answer: "dairy",
      options: ["protein", "dairy", "carbohydrates", "fats"],
      hint: "Food products made from milk, typically from cows.",
    },
    {
      emojis: ["🍝", "🍕", "🇮🇹"],
      answer: "Italian cuisine",
      options: [
        "French cuisine",
        "Italian cuisine",
        "Spanish cuisine",
        "Greek cuisine",
      ],
      hint: "A style of cooking characterized by dishes like pasta and pizza.",
    },
    {
      emojis: ["🍚", "🥢", "🍵"],
      answer: "Chinese cuisine",
      options: [
        "Japanese cuisine",
        "Korean cuisine",
        "Chinese cuisine",
        "Thai cuisine",
      ],
      hint: "A culinary style known for dishes like fried rice and dim sum.",
    },
    {
      emojis: ["🍰", "🎂", "🧁"],
      answer: "dessert",
      options: ["appetizer", "main course", "dessert", "side dish"],
      hint: "The sweet course eaten at the end of a meal.",
    },
    {
      emojis: ["🥩", "🥔", "🥕"],
      answer: "balanced diet",
      options: ["vegetarian", "balanced diet", "keto diet", "fasting"],
      hint: "A way of eating that includes a variety of different food groups.",
    },
    {
      emojis: ["🍎", "🥕", "🥦"],
      answer: "vegetarian",
      options: ["carnivore", "pescatarian", "vegetarian", "omnivore"],
      hint: "A diet that excludes meat and sometimes other animal products.",
    },
    {
      emojis: ["🍯", "🐝", "🍵"],
      answer: "natural sweetener",
      options: [
        "artificial sweetener",
        "natural sweetener",
        "sugar substitute",
        "flavor enhancer",
      ],
      hint: "A sweet substance produced by bees, often used in tea.",
    },
    {
      emojis: ["🌾", "🍞", "🥖"],
      answer: "gluten",
      options: ["protein", "carbohydrate", "gluten", "fiber"],
      hint: "A protein found in wheat and related grains, avoided by some people.",
    },
    {
      emojis: ["🥑", "🍞", "☕"],
      answer: "brunch",
      options: ["breakfast", "lunch", "brunch", "dinner"],
      hint: "A meal eaten in the late morning that combines breakfast and lunch.",
    },
    {
      emojis: ["🥘", "🍲", "🥣"],
      answer: "comfort food",
      options: [
        "gourmet cuisine",
        "diet food",
        "comfort food",
        "exotic dishes",
      ],
      hint: "Traditional dishes that provide nostalgic or sentimental value.",
    },
  ],
  animals: [
    {
      emojis: ["🐶", "🐱", "🐹"],
      answer: "mammal",
      options: ["reptile", "mammal", "amphibian", "bird"],
      hint: "This class of animals is warm-blooded and usually has fur.",
    },
    {
      emojis: ["🦁", "🐯", "🐆"],
      answer: "big cats",
      options: ["primates", "big cats", "marine mammals", "marsupials"],
      hint: "Large felines, often apex predators in their ecosystems.",
    },
    {
      emojis: ["🐘", "🦏", "🦛"],
      answer: "megafauna",
      options: ["insects", "megafauna", "reptiles", "fish"],
      hint: "Large or giant animals, often referring to those weighing over 40 kg.",
    },
    {
      emojis: ["🦅", "🦉", "🦜"],
      answer: "birds of prey",
      options: ["flightless birds", "birds of prey", "waterfowl", "songbirds"],
      hint: "Birds that hunt and feed on other animals.",
    },
    {
      emojis: ["🐒", "🦍", "🦧"],
      answer: "primates",
      options: ["carnivores", "primates", "cetaceans", "ungulates"],
      hint: "An order of mammals that includes monkeys, apes, and humans.",
    },
    {
      emojis: ["🦎", "🐍"],
      answer: "herpetology",
      options: ["ichthyology", "herpetology", "ornithology", "entomology"],
      hint: "The branch of zoology concerned with the study of amphibians and reptiles.",
    },
    {
      emojis: ["🐠", "🦈", "🐙"],
      answer: "marine life",
      options: [
        "freshwater species",
        "marine life",
        "land animals",
        "flying creatures",
      ],
      hint: "Animals that live in saltwater environments.",
    },
    {
      emojis: ["🦋", "🐝", "🐞"],
      answer: "insects",
      options: ["arachnids", "crustaceans", "insects", "mollusks"],
      hint: "A class of arthropods with six legs and often wings.",
    },
    {
      emojis: ["🐸", "🦎", "🐢"],
      answer: "cold-blooded",
      options: ["warm-blooded", "cold-blooded", "endothermic", "homeothermic"],
      hint: "Animals whose body temperature varies with their environment.",
    },
    {
      emojis: ["🦘", "🐨", "🦘"],
      answer: "marsupials",
      options: ["monotremes", "marsupials", "placentals", "mammals"],
      hint: "Mammals that carry their young in a pouch.",
    },
    {
      emojis: ["🐺", "🦊", "🐕"],
      answer: "canines",
      options: ["felines", "canines", "bovines", "equines"],
      hint: "A family of carnivorous mammals including dogs and wolves.",
    },
    {
      emojis: ["🦒", "🦓", "🦛"],
      answer: "African savanna",
      options: ["rainforest", "tundra", "African savanna", "coral reef"],
      hint: "A grassland ecosystem where these animals are commonly found.",
    },
    {
      emojis: ["🐝", "🐜", "🐛"],
      answer: "pollination",
      options: ["hibernation", "migration", "pollination", "camouflage"],
      hint: "The process of transferring pollen, often facilitated by these creatures.",
    },
    {
      emojis: ["🦅", "🐧", "🦩"],
      answer: "avian",
      options: ["mammalian", "reptilian", "avian", "amphibian"],
      hint: "Relating to or characteristic of birds.",
    },
    {
      emojis: ["🐳", "🐬", "🦭"],
      answer: "marine mammals",
      options: ["fish", "marine mammals", "cephalopods", "crustaceans"],
      hint: "Warm-blooded animals that live in the ocean.",
    },
    {
      emojis: ["🦁", "🐺", "🦊"],
      answer: "carnivores",
      options: ["herbivores", "omnivores", "carnivores", "detritivores"],
      hint: "Animals that primarily eat meat.",
    },
    {
      emojis: ["🐘", "🦏", "🦬"],
      answer: "endangered species",
      options: [
        "domestic animals",
        "farm animals",
        "endangered species",
        "extinct species",
      ],
      hint: "Animals at risk of disappearing from the wild.",
    },
    {
      emojis: ["🦋", "🐛", "🐞"],
      answer: "metamorphosis",
      options: ["symbiosis", "metamorphosis", "mimicry", "mutualism"],
      hint: "The process of transformation from an immature form to an adult form.",
    },
    {
      emojis: ["🐟", "🦐", "🦀"],
      answer: "aquatic",
      options: ["terrestrial", "arboreal", "aquatic", "aerial"],
      hint: "Living or found in or near water.",
    },
    {
      emojis: ["🦥", "🐨", "🐼"],
      answer: "herbivores",
      options: ["carnivores", "omnivores", "herbivores", "insectivores"],
      hint: "Animals that primarily eat plants.",
    },
  ],
  transport: [
    {
      emojis: ["🚗", "🚕", "🚙"],
      answer: "vehicle",
      options: ["vehicle", "building", "furniture", "appliance"],
      hint: "A general term for any form of transportation.",
    },
    {
      emojis: ["🚂", "🚅", "🚊"],
      answer: "rail transport",
      options: [
        "air transport",
        "sea transport",
        "rail transport",
        "road transport",
      ],
      hint: "A method of transport that uses a track or guideway for vehicles.",
    },
    {
      emojis: ["🛳️", "⛴️", "🚢"],
      answer: "maritime transport",
      options: [
        "aviation",
        "maritime transport",
        "public transit",
        "space travel",
      ],
      hint: "The transport of people or goods via waterways.",
    },
    {
      emojis: ["🚁", "✈️", "🛩️"],
      answer: "aviation",
      options: ["navigation", "aviation", "locomotion", "propulsion"],
      hint: "The activities surrounding mechanical flight and the aircraft industry.",
    },
    {
      emojis: ["🚗", "🔌"],
      answer: "electric vehicle",
      options: [
        "hybrid car",
        "electric vehicle",
        "fuel cell",
        "combustion engine",
      ],
      hint: "A type of vehicle that uses one or more electric motors for propulsion.",
    },
    {
      emojis: ["🚀", "🛰️", "🌌"],
      answer: "aerospace",
      options: ["aeronautics", "aerospace", "astronautics", "astrophysics"],
      hint: "The branch of technology and industry concerned with both aviation and space flight.",
    },
    {
      emojis: ["🚲", "🛴", "🛹"],
      answer: "micromobility",
      options: ["public transit", "micromobility", "carpooling", "ridesharing"],
      hint: "Small, lightweight vehicles for short-distance travel in urban areas.",
    },
    {
      emojis: ["🚗", "👥", "💰"],
      answer: "ridesharing",
      options: ["taxi service", "car rental", "ridesharing", "public transit"],
      hint: "A transportation service where passengers share vehicles, often arranged via smartphone apps.",
    },
    {
      emojis: ["🚇", "🚊", "🚉"],
      answer: "public transit",
      options: [
        "private transport",
        "public transit",
        "freight transport",
        "air travel",
      ],
      hint: "Transportation services available for use by the general public.",
    },
    {
      emojis: ["📦", "🚚", "🏭"],
      answer: "logistics",
      options: ["delivery", "shipping", "logistics", "warehousing"],
      hint: "The detailed organization and implementation of a complex operation, often related to goods transport.",
    },
    {
      emojis: ["🛣️", "🌉", "🚧"],
      answer: "infrastructure",
      options: ["vehicles", "infrastructure", "traffic", "navigation"],
      hint: "The basic physical systems of a country's or community's transportation.",
    },
    {
      emojis: ["🚗", "💨", "🌿"],
      answer: "emissions",
      options: ["fuel efficiency", "speed", "emissions", "horsepower"],
      hint: "Gases and particles released into the air by vehicles, often a focus of environmental concerns.",
    },
    {
      emojis: ["🚶‍♂️", "🚲", "🌳"],
      answer: "eco-friendly transport",
      options: [
        "motorized transport",
        "public transit",
        "eco-friendly transport",
        "high-speed travel",
      ],
      hint: "Methods of transportation that have minimal impact on the environment.",
    },
    {
      emojis: ["🚗", "📱", "🤖"],
      answer: "autonomous vehicles",
      options: [
        "connected cars",
        "electric vehicles",
        "autonomous vehicles",
        "hybrid cars",
      ],
      hint: "Vehicles capable of sensing their environment and operating without human involvement.",
    },
    {
      emojis: ["🚂", "🚃", "🛤️"],
      answer: "railway system",
      options: [
        "highway system",
        "railway system",
        "canal network",
        "airport network",
      ],
      hint: "A network of tracks, trains, and stations for transporting passengers and freight.",
    },
    {
      emojis: ["✈️", "🏢", "🛂"],
      answer: "airport",
      options: ["train station", "bus terminal", "airport", "seaport"],
      hint: "A place where aircraft take off and land, typically equipped with hard-surfaced landing strips and facilities for handling passengers.",
    },
    {
      emojis: ["🚗", "🚦", "📊"],
      answer: "traffic management",
      options: [
        "road construction",
        "vehicle maintenance",
        "traffic management",
        "driver education",
      ],
      hint: "The planning, monitoring and control of transport to enable safe, efficient movement.",
    },
    {
      emojis: ["🚗", "⛽", "💸"],
      answer: "fuel economy",
      options: ["speed limit", "fuel economy", "engine size", "vehicle weight"],
      hint: "The relationship between the distance traveled and the amount of fuel consumed by a vehicle.",
    },
    {
      emojis: ["🏙️", "🚲", "👥"],
      answer: "bike-sharing",
      options: [
        "car-sharing",
        "bike-sharing",
        "scooter-rental",
        "public transit",
      ],
      hint: "A system where bicycles are made available for shared use to individuals on a short term basis.",
    },
    {
      emojis: ["🚗", "🔋", "🔌"],
      answer: "charging station",
      options: ["gas station", "parking lot", "charging station", "car wash"],
      hint: "A place where electric vehicles can be recharged.",
    },
  ],
  sports: [
    {
      emojis: ["🏀", "⚽", "🎾"],
      answer: "sport",
      options: ["art", "music", "sport", "cooking"],
      hint: "Physical activities often involving competition.",
    },
    {
      emojis: ["🏊", "🚴", "🏃"],
      answer: "triathlon",
      options: ["pentathlon", "decathlon", "triathlon", "marathon"],
      hint: "A multi-sport event involving these three activities.",
    },
    {
      emojis: ["🥊", "🤼", "🤺"],
      answer: "combat sports",
      options: [
        "team sports",
        "water sports",
        "combat sports",
        "winter sports",
      ],
      hint: "Athletic competitions involving one-on-one physical confrontations.",
    },
    {
      emojis: ["⛷️", "🏂", "🛷"],
      answer: "winter sports",
      options: [
        "summer sports",
        "indoor sports",
        "water sports",
        "winter sports",
      ],
      hint: "Athletic activities that are played on snow or ice.",
    },
    {
      emojis: ["🏋️", "💪"],
      answer: "strength training",
      options: ["cardio", "flexibility", "strength training", "balance"],
      hint: "Physical exercise specializing in the use of resistance to induce muscular contraction.",
    },
    {
      emojis: ["🧘", "🧠", "😌"],
      answer: "mindfulness",
      options: ["endurance", "agility", "mindfulness", "coordination"],
      hint: "The practice of maintaining a nonjudgmental state of heightened or complete awareness of one's thoughts, emotions, or experiences on a moment-to-moment basis.",
    },
    {
      emojis: ["🏆", "🥇", "🏅"],
      answer: "Olympics",
      options: ["World Cup", "Olympics", "Super Bowl", "World Series"],
      hint: "A major international multi-sport event held every four years.",
    },
    {
      emojis: ["🏈", "🏉", "🥅"],
      answer: "football",
      options: ["basketball", "football", "hockey", "soccer"],
      hint: "A popular sport involving an oval-shaped ball and end zones.",
    },
    {
      emojis: ["🏸", "🥍", "🏑"],
      answer: "racket sports",
      options: [
        "ball sports",
        "racket sports",
        "water sports",
        "extreme sports",
      ],
      hint: "A category of sports that use a racket or stick to hit a ball or shuttlecock.",
    },
    {
      emojis: ["🧗‍♀️", "🚵‍♂️", "🏄‍♂️"],
      answer: "extreme sports",
      options: [
        "team sports",
        "individual sports",
        "extreme sports",
        "Paralympic sports",
      ],
      hint: "Sports involving high speed, height, real or perceived danger.",
    },
    {
      emojis: ["⚾", "🥎", "🏏"],
      answer: "batting sports",
      options: [
        "kicking sports",
        "throwing sports",
        "batting sports",
        "catching sports",
      ],
      hint: "Sports where a ball is hit with a bat or similar implement.",
    },
    {
      emojis: ["🏋️‍♀️", "🤸‍♂️", "🤾‍♀️"],
      answer: "gymnastics",
      options: ["athletics", "gymnastics", "acrobatics", "weightlifting"],
      hint: "A sport involving exercises that require balance, strength, flexibility, agility, coordination, and endurance.",
    },
    {
      emojis: ["🎯", "🏹", "🔫"],
      answer: "target sports",
      options: [
        "combat sports",
        "target sports",
        "ball sports",
        "water sports",
      ],
      hint: "Sports that test accuracy and precision in aiming at a target.",
    },
    {
      emojis: ["🧠", "♟️", "🃏"],
      answer: "mind sports",
      options: ["board games", "mind sports", "card games", "video games"],
      hint: "Competitive activities of intellectual skill, often not involving physical exertion.",
    },
    {
      emojis: ["🤼‍♂️", "🥋", "🥊"],
      answer: "martial arts",
      options: ["wrestling", "boxing", "martial arts", "fencing"],
      hint: "A group of fighting and self-defense practices from various traditions.",
    },
    {
      emojis: ["🏃‍♀️", "🚶‍♂️", "🚴‍♀️"],
      answer: "endurance sports",
      options: [
        "sprint sports",
        "endurance sports",
        "team sports",
        "winter sports",
      ],
      hint: "Sports that require sustained physical effort over a long period.",
    },
    {
      emojis: ["🏒", "⛸️", "🥌"],
      answer: "ice sports",
      options: ["water sports", "ice sports", "snow sports", "indoor sports"],
      hint: "Sports played on frozen surfaces, typically involving ice skates.",
    },
    {
      emojis: ["🚣‍♀️", "🏄‍♂️", "🤽‍♂️"],
      answer: "water sports",
      options: ["land sports", "air sports", "water sports", "beach sports"],
      hint: "Sports practiced in or on bodies of water.",
    },
    {
      emojis: ["🎳", "🎱", "🥏"],
      answer: "precision sports",
      options: [
        "strength sports",
        "speed sports",
        "precision sports",
        "endurance sports",
      ],
      hint: "Sports that require high accuracy in aiming or positioning objects.",
    },
    {
      emojis: ["🏇", "🐎", "🤠"],
      answer: "equestrian sports",
      options: ["racing sports", "equestrian sports", "rodeo", "polo"],
      hint: "Sports involving horseback riding and horsemanship.",
    },
  ],
  nature: [
    {
      emojis: ["🌳", "🌿", "🍄"],
      answer: "ecosystem",
      options: ["economy", "ecosystem", "society", "galaxy"],
      hint: "A biological community of interacting organisms and their physical environment.",
    },
    {
      emojis: ["🌋", "🏔️", "🏜️"],
      answer: "landforms",
      options: [
        "weather patterns",
        "landforms",
        "water bodies",
        "atmospheric layers",
      ],
      hint: "Natural features of the Earth's surface.",
    },
    {
      emojis: ["🌊", "🌬️", "☀️"],
      answer: "weather",
      options: ["climate", "weather", "season", "atmosphere"],
      hint: "The day-to-day state of the atmosphere, and its short-term variation.",
    },
    {
      emojis: ["🐝", "🦋", "🐞"],
      answer: "pollinators",
      options: ["predators", "pollinators", "decomposers", "producers"],
      hint: "Animals that help plants reproduce by transferring pollen.",
    },
    {
      emojis: ["🌡️", "🌍", "🏭"],
      answer: "global warming",
      options: ["deforestation", "global warming", "biodiversity", "pollution"],
      hint: "The long-term heating of Earth's climate system observed since the pre-industrial period.",
    },
    {
      emojis: ["🌳", "🐘", "🐒"],
      answer: "biodiversity",
      options: ["ecosystem", "habitat", "biodiversity", "conservation"],
      hint: "The variety of life in the world or in a particular habitat or ecosystem.",
    },
    {
      emojis: ["🌿", "🍃", "🌱"],
      answer: "photosynthesis",
      options: [
        "respiration",
        "photosynthesis",
        "fermentation",
        "decomposition",
      ],
      hint: "The process by which plants use sunlight to produce energy from carbon dioxide and water.",
    },
    {
      emojis: ["🦁", "🐰", "🦊"],
      answer: "food chain",
      options: ["ecosystem", "food chain", "symbiosis", "migration"],
      hint: "A series of organisms each dependent on the next as a source of food.",
    },
    {
      emojis: ["🌳", "🔥", "🌱"],
      answer: "forest fire ecology",
      options: [
        "deforestation",
        "forest fire ecology",
        "reforestation",
        "slash-and-burn",
      ],
      hint: "The study of how fire affects forest ecosystems and their regeneration.",
    },
    {
      emojis: ["🌊", "🐠", "🐙"],
      answer: "marine biology",
      options: ["oceanography", "marine biology", "limnology", "ichthyology"],
      hint: "The scientific study of organisms in the ocean or other marine bodies of water.",
    },
    {
      emojis: ["🦠", "🍄", "🍂"],
      answer: "decomposers",
      options: ["producers", "consumers", "decomposers", "scavengers"],
      hint: "Organisms that break down dead plant and animal matter.",
    },
    {
      emojis: ["🌡️", "🌊", "💨"],
      answer: "climate",
      options: ["weather", "season", "climate", "atmosphere"],
      hint: "The average weather conditions in an area over a long period.",
    },
    {
      emojis: ["🌳", "🌲", "🌴"],
      answer: "forest",
      options: ["jungle", "forest", "savanna", "tundra"],
      hint: "A large area covered chiefly with trees and undergrowth.",
    },
    {
      emojis: ["🐝", "🌼", "🍯"],
      answer: "pollination",
      options: [
        "germination",
        "pollination",
        "fertilization",
        "photosynthesis",
      ],
      hint: "The transfer of pollen from a male part of a plant to a female part of a plant, enabling later fertilization.",
    },
    {
      emojis: ["🦅", "🐟", "🌳"],
      answer: "habitat",
      options: ["ecosystem", "biome", "habitat", "niche"],
      hint: "The natural home or environment of an animal, plant, or other organism.",
    },
    {
      emojis: ["🌱", "🌿", "🌳"],
      answer: "plant growth",
      options: ["evolution", "adaptation", "plant growth", "succession"],
      hint: "The process by which plants increase in size and develop from a seed to a mature plant.",
    },
    {
      emojis: ["🦋", "🐛", "🐞"],
      answer: "metamorphosis",
      options: ["symbiosis", "metamorphosis", "mimicry", "molting"],
      hint: "A profound change in form from one stage to the next in the life history of an organism.",
    },
    {
      emojis: ["🌑", "🌓", "🌕"],
      answer: "lunar phases",
      options: [
        "solar eclipse",
        "lunar phases",
        "planetary alignment",
        "asteroid belt",
      ],
      hint: "The changing appearance of the moon as seen from earth.",
    },
    {
      emojis: ["🌊", "🏖️", "🏔️"],
      answer: "erosion",
      options: ["sedimentation", "erosion", "weathering", "deposition"],
      hint: "The process of earth being worn away, often by water, wind, or ice.",
    },
    {
      emojis: ["🦁", "🐘", "🦒"],
      answer: "savanna",
      options: ["rainforest", "tundra", "savanna", "desert"],
      hint: "A grassy plain in tropical and subtropical regions, with few trees.",
    },
  ],
  technology: [
    {
      emojis: ["💻", "📱", "🤖"],
      answer: "digital",
      options: ["analog", "digital", "organic", "mechanical"],
      hint: "Relating to computer technology and electronic systems.",
    },
    {
      emojis: ["🔋", "💡", "🔌"],
      answer: "electricity",
      options: ["magnetism", "gravity", "electricity", "nuclear power"],
      hint: "A form of energy resulting from the existence of charged particles.",
    },
    {
      emojis: ["📡", "🛰️", "🔭"],
      answer: "telecommunications",
      options: [
        "transportation",
        "telecommunications",
        "manufacturing",
        "agriculture",
      ],
      hint: "The transmission of information by various types of technologies over wire, radio, optical, or other electromagnetic systems.",
    },
    {
      emojis: ["🧬", "💊", "🔬"],
      answer: "biotechnology",
      options: [
        "nanotechnology",
        "biotechnology",
        "robotics",
        "quantum computing",
      ],
      hint: "Technology that utilizes biological systems, living organisms, or their derivatives to develop or create different products.",
    },
    {
      emojis: ["🤖", "🧠", "💻"],
      answer: "artificial intelligence",
      options: [
        "virtual reality",
        "artificial intelligence",
        "quantum computing",
        "blockchain",
      ],
      hint: "The simulation of human intelligence processes by machines, especially computer systems.",
    },
    {
      emojis: ["🔒", "🔑", "📊"],
      answer: "blockchain",
      options: [
        "encryption",
        "blockchain",
        "quantum cryptography",
        "steganography",
      ],
      hint: "A decentralized, distributed ledger technology that records transactions across many computers.",
    },
    {
      emojis: ["👓", "🖥️"],
      answer: "augmented reality",
      options: [
        "virtual reality",
        "augmented reality",
        "holography",
        "3D printing",
      ],
      hint: "An interactive experience where the real-world environment is enhanced with computer-generated information.",
    },
    {
      emojis: ["🌐", "💻", "📱"],
      answer: "internet",
      options: ["intranet", "internet", "ethernet", "bluetooth"],
      hint: "A global network of interconnected computer networks.",
    },
    {
      emojis: ["☁️", "💾", "📤"],
      answer: "cloud computing",
      options: [
        "data mining",
        "cloud computing",
        "edge computing",
        "grid computing",
      ],
      hint: "The delivery of computing services over the internet.",
    },
    {
      emojis: ["🔒", "🖥️", "🦠"],
      answer: "cybersecurity",
      options: ["firewall", "antivirus", "cybersecurity", "encryption"],
      hint: "The practice of protecting systems, networks, and programs from digital attacks.",
    },
    {
      emojis: ["📊", "💹", "🧮"],
      answer: "data analytics",
      options: [
        "statistics",
        "data analytics",
        "machine learning",
        "data mining",
      ],
      hint: "The process of examining data sets to draw conclusions about the information they contain.",
    },
    {
      emojis: ["🤖", "🏭", "🦾"],
      answer: "automation",
      options: [
        "robotics",
        "automation",
        "manufacturing",
        "artificial intelligence",
      ],
      hint: "The use of machines, control systems, and information technologies to optimize productivity.",
    },
    {
      emojis: ["📱", "💳", "💸"],
      answer: "fintech",
      options: ["e-commerce", "fintech", "cryptocurrency", "mobile banking"],
      hint: "Computer programs and other technology used to support or enable banking and financial services.",
    },
    {
      emojis: ["🔬", "🧬", "💊"],
      answer: "bioengineering",
      options: ["bioengineering", "pharmacology", "genetics", "biotechnology"],
      hint: "The application of engineering principles to biology and medical systems.",
    },
    {
      emojis: ["🛰️", "📡", "🌍"],
      answer: "GPS",
      options: ["radar", "sonar", "GPS", "lidar"],
      hint: "A satellite-based navigation system that provides location and time information.",
    },
    {
      emojis: ["🔋", "🚗", "🔌"],
      answer: "electric vehicle",
      options: [
        "hybrid car",
        "electric vehicle",
        "solar car",
        "fuel cell vehicle",
      ],
      hint: "A vehicle that uses one or more electric motors for propulsion.",
    },
    {
      emojis: ["👤", "📸", "🔓"],
      answer: "biometrics",
      options: [
        "surveillance",
        "biometrics",
        "facial recognition",
        "cryptography",
      ],
      hint: "The measurement and statistical analysis of people's unique physical and behavioral characteristics.",
    },
    {
      emojis: ["🖨️", "🔩", "🛠️"],
      answer: "3D printing",
      options: ["manufacturing", "prototyping", "3D printing", "CNC machining"],
      hint: "The construction of a three-dimensional object from a digital 3D model.",
    },
    {
      emojis: ["🕹️", "👓", "🖥️"],
      answer: "virtual reality",
      options: [
        "augmented reality",
        "virtual reality",
        "mixed reality",
        "simulation",
      ],
      hint: "A simulated experience that can be similar to or completely different from the real world.",
    },
    {
      emojis: ["🔬", "⚛️", "💻"],
      answer: "nanotechnology",
      options: [
        "microscopy",
        "nanotechnology",
        "quantum computing",
        "molecular biology",
      ],
      hint: "The manipulation of matter on an atomic, molecular, and supramolecular scale.",
    },
  ],
  science: [
    {
      emojis: ["🧬", "🔬", "💊"],
      answer: "biotechnology",
      options: ["chemistry", "biotechnology", "physics", "geology"],
      hint: "The use of living systems and organisms to develop or make products.",
    },
    {
      emojis: ["🌋", "🌡️"],
      answer: "geothermal",
      options: ["seismic", "geothermal", "atmospheric", "tectonic"],
      hint: "Relating to or produced by the internal heat of the earth.",
    },
    {
      emojis: ["🔬", "🧫", "🦠"],
      answer: "microbiology",
      options: ["astronomy", "microbiology", "ecology", "genetics"],
      hint: "The study of microorganisms, such as bacteria and viruses.",
    },
    {
      emojis: ["🌌", "🕳️"],
      answer: "black hole",
      options: ["galaxy", "nebula", "black hole", "supernova"],
      hint: "A region of spacetime where gravity is so strong that nothing can escape from it.",
    },
    {
      emojis: ["⚛️", "🔬"],
      answer: "quantum mechanics",
      options: [
        "relativity",
        "quantum mechanics",
        "thermodynamics",
        "electromagnetism",
      ],
      hint: "The fundamental theory of nature at the smallest scales of energy levels of atoms and subatomic particles.",
    },
    {
      emojis: ["🧪", "🔥", "💨"],
      answer: "chemical reaction",
      options: [
        "physical change",
        "chemical reaction",
        "nuclear decay",
        "phase transition",
      ],
      hint: "A process that leads to the transformation of one set of chemical substances to another.",
    },
    {
      emojis: ["🧬", "🔀", "🐁"],
      answer: "CRISPR",
      options: ["CRISPR", "PCR", "Electrophoresis", "Southern blot"],
      hint: "A gene-editing technology that allows for precise modifications of DNA sequences.",
    },
    {
      emojis: ["🌌", "🌀", "🕳️"],
      answer: "quasar",
      options: ["nebula", "quasar", "pulsar", "magnetar"],
      hint: "An extremely luminous active galactic nucleus, powered by a supermassive black hole.",
    },
    {
      emojis: ["🧠", "⚡", "💊"],
      answer: "neurotransmitter",
      options: [
        "synapse",
        "neurotransmitter",
        "action potential",
        "myelin sheath",
      ],
      hint: "Chemical messengers that transmit signals across a chemical synapse.",
    },
    {
      emojis: ["🧲", "⚡", "💡"],
      answer: "electromagnetism",
      options: ["thermodynamics", "mechanics", "electromagnetism", "optics"],
      hint: "The fundamental force involving the interaction between electrically charged particles.",
    },
    {
      emojis: ["🌡️", "🔥", "❄️"],
      answer: "thermodynamics",
      options: ["fluid dynamics", "thermodynamics", "acoustics", "kinematics"],
      hint: "The branch of physics dealing with heat and temperature and their relation to energy and work.",
    },
    {
      emojis: ["🧬", "👪", "🔬"],
      answer: "genetics",
      options: ["evolution", "genetics", "embryology", "ecology"],
      hint: "The study of heredity and the variation of inherited characteristics.",
    },
    {
      emojis: ["🦕", "🏔️", "⏳"],
      answer: "paleontology",
      options: ["archaeology", "geology", "paleontology", "anthropology"],
      hint: "The study of fossils as a guide to the history of life on Earth.",
    },
    {
      emojis: ["🌍", "🌋", "💎"],
      answer: "geology",
      options: ["meteorology", "geology", "oceanography", "seismology"],
      hint: "The science that deals with the Earth's physical structure and substance.",
    },
    {
      emojis: ["🔭", "🌠", "🪐"],
      answer: "astronomy",
      options: ["cosmology", "astrophysics", "astronomy", "planetology"],
      hint: "The scientific study of celestial objects, space, and the physical universe as a whole.",
    },
    {
      emojis: ["🌱", "🌳", "🍃"],
      answer: "botany",
      options: ["ecology", "botany", "agriculture", "horticulture"],
      hint: "The scientific study of plants, including their physiology, structure, and ecology.",
    },
    {
      emojis: ["💊", "🧪", "👨‍⚕️"],
      answer: "pharmacology",
      options: ["toxicology", "pharmacology", "medicine", "biochemistry"],
      hint: "The branch of medicine concerned with the uses, effects, and modes of action of drugs.",
    },
    {
      emojis: ["🧠", "🤔", "🧪"],
      answer: "neuroscience",
      options: [
        "psychology",
        "neuroscience",
        "psychiatry",
        "cognitive science",
      ],
      hint: "The scientific study of the nervous system and brain.",
    },
    {
      emojis: ["🌊", "🐠", "🌡️"],
      answer: "oceanography",
      options: ["marine biology", "oceanography", "hydrology", "climatology"],
      hint: "The branch of science that deals with the physical and biological properties of the ocean.",
    },
    {
      emojis: ["💉", "🦠", "🛡️"],
      answer: "immunology",
      options: ["virology", "immunology", "epidemiology", "pathology"],
      hint: "The branch of medicine and biology concerned with immunity.",
    },
  ],
  culture: [
    {
      emojis: ["🎭", "📚", "🎨"],
      answer: "humanities",
      options: ["fine arts", "humanities", "social sciences", "liberal arts"],
      hint: "Academic disciplines that study human culture and experience.",
    },
    {
      emojis: ["🗣️", "🌐"],
      answer: "globalization",
      options: ["immigration", "globalization", "diplomacy", "trade"],
      hint: "The process by which businesses or other organizations develop international influence or start operating on an international scale.",
    },
    {
      emojis: ["👥", "💬", "🤝"],
      answer: "intercultural communication",
      options: [
        "sociology",
        "anthropology",
        "intercultural communication",
        "linguistics",
      ],
      hint: "The study of communication across different cultures and social groups.",
    },
    {
      emojis: ["🏛️", "📜"],
      answer: "cultural heritage",
      options: ["archaeology", "cultural heritage", "history", "museology"],
      hint: "The legacy of physical artifacts and intangible attributes of a group or society that are inherited from past generations.",
    },
    {
      emojis: ["🎭", "🎬", "📺"],
      answer: "performing arts",
      options: [
        "visual arts",
        "performing arts",
        "literary arts",
        "culinary arts",
      ],
      hint: "Forms of creative activity that are performed in front of an audience, such as drama, music, and dance.",
    },
    {
      emojis: ["🗿", "🏺", "⚱️"],
      answer: "archaeology",
      options: ["paleontology", "archaeology", "anthropology", "geology"],
      hint: "The study of human history and prehistory through the excavation of sites and the analysis of artifacts and other physical remains.",
    },
    {
      emojis: ["🎭", "🎼", "🖼️"],
      answer: "fine arts",
      options: ["pop culture", "fine arts", "folk art", "applied arts"],
      hint: "Creative art, especially visual art, whose products are to be appreciated primarily or solely for their imaginative, aesthetic, or intellectual content.",
    },
    {
      emojis: ["👗", "👘", "👠"],
      answer: "fashion",
      options: ["costume", "uniform", "fashion", "disguise"],
      hint: "A popular trend, especially in styles of dress and ornament or manners of behavior.",
    },
    {
      emojis: ["🍣", "🍕", "🌮"],
      answer: "cuisine",
      options: ["diet", "recipe", "cuisine", "nutrition"],
      hint: "A style or method of cooking, especially as characteristic of a particular country, region, or establishment.",
    },
    {
      emojis: ["🎉", "🎊", "🥳"],
      answer: "festivals",
      options: ["parties", "ceremonies", "festivals", "rituals"],
      hint: "Periodic celebrations or commemorations, often with cultural or religious significance.",
    },
    {
      emojis: ["🗣️", "✍️", "📖"],
      answer: "literature",
      options: ["journalism", "literature", "linguistics", "rhetoric"],
      hint: "Written works, especially those considered of superior or lasting artistic merit.",
    },
    {
      emojis: ["🏛️", "🕌", "⛪"],
      answer: "architecture",
      options: ["sculpture", "painting", "architecture", "landscaping"],
      hint: "The art or practice of designing and constructing buildings.",
    },
    {
      emojis: ["👑", "👸", "🤴"],
      answer: "monarchy",
      options: ["democracy", "monarchy", "oligarchy", "anarchy"],
      hint: "A form of government with a monarch at the head.",
    },
    {
      emojis: ["🎨", "🖌️", "🖼️"],
      answer: "visual arts",
      options: [
        "performing arts",
        "visual arts",
        "literary arts",
        "culinary arts",
      ],
      hint: "Art forms that create works that are primarily visual in nature.",
    },
    {
      emojis: ["🧕", "👳‍♂️", "🕋"],
      answer: "religion",
      options: ["philosophy", "mythology", "religion", "spirituality"],
      hint: "The belief in and worship of a superhuman controlling power, especially a personal God or gods.",
    },
    {
      emojis: ["🗳️", "🏛️", "⚖️"],
      answer: "politics",
      options: ["economics", "sociology", "politics", "anthropology"],
      hint: "The activities associated with the governance of a country or other area.",
    },
    {
      emojis: ["🏺", "🖼️", "💎"],
      answer: "artifacts",
      options: ["relics", "artifacts", "antiques", "fossils"],
      hint: "Objects made by human beings, typically of cultural or historical interest.",
    },
    {
      emojis: ["🗿", "🏰", "🕍"],
      answer: "historical sites",
      options: ["landmarks", "monuments", "historical sites", "ruins"],
      hint: "Places of historical significance, often preserved for public interest.",
    },
    {
      emojis: ["🎓", "📚", "🏫"],
      answer: "education",
      options: ["research", "training", "education", "indoctrination"],
      hint: "The process of receiving or giving systematic instruction, especially at a school or university.",
    },
    {
      emojis: ["💃", "🕺", "🩰"],
      answer: "dance",
      options: ["exercise", "sport", "dance", "yoga"],
      hint: "Movements of the body, usually rhythmic and to music, used as a form of expression or social interaction.",
    },
  ],
  everyday_life: [
    {
      emojis: ["🛏️", "⏰", "🌅"],
      answer: "wake up",
      options: ["sleep in", "wake up", "take a nap", "hit snooze"],
      hint: "The act of rising from sleep, often accompanied by an alarm.",
    },
    {
      emojis: ["🚿", "🧼", "🎵"],
      answer: "shower singing",
      options: ["bath time", "shower singing", "water dance", "soap opera"],
      hint: "A common habit of performing vocal exercises while bathing.",
    },
    {
      emojis: ["📱", "👍", "💬"],
      answer: "social media",
      options: ["texting", "phone call", "social media", "email"],
      hint: "Online platforms for sharing content and interacting with others.",
    },
    {
      emojis: ["🏠", "🧹", "🧼"],
      answer: "spring cleaning",
      options: [
        "house party",
        "spring cleaning",
        "home renovation",
        "feng shui",
      ],
      hint: "An annual tradition of thoroughly cleaning one's living space.",
    },
    {
      emojis: ["🛒", "📝", "🏪"],
      answer: "grocery shopping",
      options: [
        "window shopping",
        "online shopping",
        "grocery shopping",
        "bargain hunting",
      ],
      hint: "The task of purchasing food and household supplies.",
    },
    {
      emojis: ["☕", "👔", "🚶‍♂️"],
      answer: "commute",
      options: ["breakfast", "commute", "coffee break", "business meeting"],
      hint: "The daily journey to and from work",
    },
    {
      emojis: ["📺", "🛋️", "🍿"],
      answer: "binge-watching",
      options: ["movie night", "binge-watching", "home theater", "TV dinner"],
      hint: "Watching multiple episodes of a show in one sitting",
    },
    {
      emojis: ["🧺", "👕", "🧴"],
      answer: "laundry day",
      options: [
        "spring cleaning",
        "laundry day",
        "dry cleaning",
        "wardrobe organization",
      ],
      hint: "A regular chore involving washing and drying clothes",
    },
    {
      emojis: ["🔔", "🚪", "📦"],
      answer: "package delivery",
      options: [
        "house guest",
        "package delivery",
        "door-to-door sales",
        "home security",
      ],
      hint: "Receiving an order at your doorstep",
    },
    {
      emojis: ["🍽️", "🧽", "💧"],
      answer: "washing dishes",
      options: [
        "cooking",
        "washing dishes",
        "water conservation",
        "kitchen cleaning",
      ],
      hint: "A post-meal cleanup activity",
    },
    {
      emojis: ["📆", "✏️", "⏰"],
      answer: "scheduling",
      options: [
        "time management",
        "scheduling",
        "calendar marking",
        "appointment setting",
      ],
      hint: "Organizing one's time and activities",
    },
    {
      emojis: ["🛒", "💳", "🧾"],
      answer: "checkout",
      options: [
        "window shopping",
        "checkout",
        "price comparison",
        "bargain hunting",
      ],
      hint: "The final step in a shopping process",
    },
    {
      emojis: ["🚗", "🔧", "💰"],
      answer: "car maintenance",
      options: [
        "road trip",
        "car maintenance",
        "auto shopping",
        "driving lesson",
      ],
      hint: "Regular upkeep to keep a vehicle running smoothly",
    },
    {
      emojis: ["📱", "🔋", "🔌"],
      answer: "charging phone",
      options: ["texting", "charging phone", "app update", "phone call"],
      hint: "Replenishing a mobile device's battery",
    },
    {
      emojis: ["🥱", "🛏️", "🌙"],
      answer: "bedtime routine",
      options: ["nap time", "bedtime routine", "sleepwalking", "night shift"],
      hint: "Evening rituals before sleep",
    },
    {
      emojis: ["🔑", "🚶‍♀️", "🏠"],
      answer: "coming home",
      options: ["house hunting", "coming home", "locking up", "moving out"],
      hint: "Returning to one's residence",
    },
    {
      emojis: ["📧", "💼", "👥"],
      answer: "networking",
      options: ["job hunting", "networking", "email marketing", "social media"],
      hint: "Building professional relationships",
    },
    {
      emojis: ["🖨️", "📄", "😠"],
      answer: "paper jam",
      options: ["office work", "paper jam", "document signing", "photocopying"],
      hint: "A common frustration with printing devices",
    },
    {
      emojis: ["🍽️", "📱", "🤳"],
      answer: "food photography",
      options: [
        "dining out",
        "food photography",
        "meal planning",
        "restaurant review",
      ],
      hint: "Capturing images of meals for social media",
    },
    {
      emojis: ["🛍️", "👚", "🏷️"],
      answer: "clothes shopping",
      options: [
        "fashion show",
        "clothes shopping",
        "laundry sorting",
        "wardrobe styling",
      ],
      hint: "Purchasing new garments",
    },
  ],
};
